## default
#spring:
#  profiles:
#    active: dev
#  jpa:
#    open-in-view: false
#    properties.hibernate.enable_lazy_load_no_trans: true
#  jackson.serialization.FAIL_ON_EMPTY_BEANS: false
#
#---
#
#spring:
#  profiles: local
#
#---
#
#spring:
#  profiles: dev
#  datasource:
##    url: jdbc:mysql:replication://with-place-rds-write.abouthere.kr:3306,with-place-rds-read.abouthere.kr:3306/Kakarot??useCursors=false&sendStringParametersAsUnicode=false&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&autoReconnect=true&allowMasterDownConnections=true&allowSlaveDownConnections=true&readFromMasterWhenNoSlaves=true
#    url: jdbc:mysql:replication://with-place-rds-write.abouthere.kr:3306,with-place-rds-read.abouthere.kr:3306/Kakarot??useCursors=false&sendStringParametersAsUnicode=false&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&autoReconnect=true
#    username: src_kakarot
#    password: uDSnr4eZ6ZZ9
#    driverClassName: com.mysql.jdbc.Driver
#  jpa:
#    generate-ddl: false
#    hibernate:
#      naming:
#        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#    show-sql: true
#    properties.hibernate.format-sql: true
#
#---
#
#spring:
#  profiles: stage
#
#---
#
#spring:
#  profiles: production

# common
spring:
  profiles:
    include:
    - core

---
spring.profiles: local

---
spring.profiles: dev

---
spring.profiles: stage

---
spring.profiles: production
