## default
#spring:
#  profiles:
#    active: dev
#  jpa:
#    open-in-view: false
#    properties.hibernate.enable_lazy_load_no_trans: true
#  jackson.serialization.FAIL_ON_EMPTY_BEANS: false
#
#---
#
#spring:
#  profiles: local
#
#---
#
#spring:
#  profiles: dev
#  datasource:

#    driverClassName: com.mysql.jdbc.Driver
#  jpa:
#    generate-ddl: false
#    hibernate:
#      naming:
#        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#    show-sql: true
#    properties.hibernate.format-sql: true
#
#---
#
#spring:
#  profiles: stage
#
#---
#
#spring:
#  profiles: production

# common
spring:
  profiles:
    include:
    - core

---
spring.profiles: local

---
spring.profiles: dev

---
spring.profiles: stage

---
spring.profiles: production
