spring:
  profiles:
    active: local

---
spring.profiles: local
spring:
  datasource:
    url: jdbc:mysql:replication://with-place-rds-write.abouthere.kr:3306,with-place-rds-read.abouthere.kr:3306/Kakarot??useCursors=false&sendStringParametersAsUnicode=false&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&autoReconnect=true
    username: src_kakarot
    password: uDSnr4eZ6ZZ9
    driverClassName: com.mysql.jdbc.Driver
  jpa:
    generate-ddl: false
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties.hibernate.format-sql: true

---
spring.profiles: dev
spring:
  datasource:
    url: jdbc:mysql:replication://with-place-rds-write.abouthere.kr:3306,with-place-rds-read.abouthere.kr:3306/Kakarot??useCursors=false&sendStringParametersAsUnicode=false&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&autoReconnect=true
    username: src_kakarot
    password: uDSnr4eZ6ZZ9
    driverClassName: com.mysql.jdbc.Driver
  jpa:
    generate-ddl: false
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties.hibernate.format-sql: true

---
spring.profiles: stage
spring:
  datasource:
    url: jdbc:mysql:replication://with-place-rds-write.abouthere.kr:3306,with-place-rds-read.abouthere.kr:3306/Kakarot??useCursors=false&sendStringParametersAsUnicode=false&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&autoReconnect=true
    username: src_kakarot
    password: uDSnr4eZ6ZZ9
    driverClassName: com.mysql.jdbc.Driver
  jpa:
    generate-ddl: false
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties.hibernate.format-sql: true

---
spring.profiles: production
spring:
  datasource:
    url: jdbc:mysql:replication://with-place-rds-write.abouthere.kr:3306,with-place-rds-read.abouthere.kr:3306/Kakarot??useCursors=false&sendStringParametersAsUnicode=false&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&autoReconnect=true
    username: src_kakarot
    password: uDSnr4eZ6ZZ9
    driverClassName: com.mysql.jdbc.Driver
  jpa:
    generate-ddl: false
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
